export const LOAD_STATUSES = [
  'Rascunho',
  'Aguardando aprovação',
  'Aprovada',
  'Aguardando fornecedor',
  'Pedido realizado',
  'Pedido confirmado',
  'Aguardando recebimento',
  'Produto recebido',
  'Em preparação',
  'Separando',
  'Etiquetando',
  'Aguardando NF',
  'Pronta para agendamento',
  'Agendada',
  'Pronta para coleta',
  'Carregada',
  'Em trânsito',
  'Entregue',
  'Finalizada',
  'Cancelada',
  'Com divergência',
] as const;

export type LoadStatus = (typeof LOAD_STATUSES)[number];
